package app.onym.android.moderation

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test

/**
 * Pinned byte-for-byte to the **normative** fixtures published by the
 * enforcement backend (onym-moderation `android/fixtures/
 * payload-fixtures.json`, generated by its `src/payload.rs`). If these
 * fail, this client drifted — the fixtures do not move to accommodate
 * it.
 *
 * Inputs: timestamp `2026-08-08T12:00:00Z`, userKey `onym:key:aabb`,
 * challenge = the 32 bytes 0x00..0x1f, mandateRef `mandate-ref-1`.
 */
class SignedSessionPayloadTest {
    private val timestamp = "2026-08-08T12:00:00Z"
    private val userKey = "onym:key:aabb"
    private val challenge = ByteArray(32) { it.toByte() }

    @Test
    fun `enrollment payload matches the backend fixture`() {
        val payload = SignedSessionPayload.enrollment(challenge, userKey, timestamp)
        assertEquals(
            "000000216f6e796d2d6d6f6465726174696f6e2d616e64726f69642d656e726f" +
                "6c6c2d763100000020000102030405060708090a0b0c0d0e0f10111213141516" +
                "1718191a1b1c1d1e1f0000000d6f6e796d3a6b65793a61616262000000143230" +
                "32362d30382d30385431323a30303a30305a00000000",
            payload.toHex(),
        )
        assertEquals(
            "MjdGYuAzA2yGT0TFKvav9Iopz4YbP0keGnh61SJ1QPU",
            SignedSessionPayload.requestHash(payload),
        )
    }

    @Test
    fun `gate payload matches the backend fixture`() {
        val payload =
            SignedSessionPayload.gateCheck(challenge, userKey, "mandate-ref-1", timestamp)
        assertEquals(
            "0000001f6f6e796d2d6d6f6465726174696f6e2d616e64726f69642d67617465" +
                "2d763100000020000102030405060708090a0b0c0d0e0f101112131415161718" +
                "191a1b1c1d1e1f0000000d6f6e796d3a6b65793a616162620000001432303236" +
                "2d30382d30385431323a30303a30305a0000000d6d616e646174652d7265662d" +
                "31",
            payload.toHex(),
        )
        assertEquals(
            "faELd9vZwOtBP14VochzXfc08GopZmrZCc8XeVD6jkY",
            SignedSessionPayload.requestHash(payload),
        )
    }

    @Test
    fun `gate payload without a mandate ref matches the backend fixture`() {
        val payload = SignedSessionPayload.gateCheck(challenge, userKey, null, timestamp)
        assertEquals(
            "0000001f6f6e796d2d6d6f6465726174696f6e2d616e64726f69642d67617465" +
                "2d763100000020000102030405060708090a0b0c0d0e0f101112131415161718" +
                "191a1b1c1d1e1f0000000d6f6e796d3a6b65793a616162620000001432303236" +
                "2d30382d30385431323a30303a30305a00000000",
            payload.toHex(),
        )
        assertEquals(
            "kuaMPqtf-bLFKROyTPUnD_4TdyJ9ImSQOuEDzMbbfK4",
            SignedSessionPayload.requestHash(payload),
        )
    }

    /** The property length-prefixing exists for: no two different
     * field splits may produce the same bytes. */
    @Test
    fun `field boundaries are unambiguous`() {
        assertNotEquals(
            SignedSessionPayload.enrollment("ab".toByteArray(), "c", "t").toHex(),
            SignedSessionPayload.enrollment("a".toByteArray(), "bc", "t").toHex(),
        )
    }

    @Test
    fun `enrollment and gate payloads are domain separated`() {
        assertNotEquals(
            SignedSessionPayload.enrollment(challenge, userKey, timestamp).toHex(),
            SignedSessionPayload.gateCheck(challenge, userKey, null, timestamp).toHex(),
        )
    }

    /** A signature minted for the iOS profile must be inert here. */
    @Test
    fun `contexts differ from the iOS profile`() {
        assertNotEquals("onym-moderation-enroll-v1", SignedSessionPayload.ENROLL_CONTEXT)
        assertNotEquals("onym-moderation-gate-v1", SignedSessionPayload.GATE_CONTEXT)
    }

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}
